openapi: 3.1.0
info:
  title: Word Counter API
  version: 1.0.0
  description: Count the number of words in a text input.
servers:
  - url: https://word-counter-samarodev.replit.app
paths:
  /count:
    post:
      operationId: countWords
      summary: Count words
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to count
      responses:
        '200':
          description: Word count result
          content:
            application/json:
              schema:
                type: object
                properties:
                  word_count:
                    type: integer
                    description: Total number of words
  /match:
    post:
      operationId: matchWords
      summary: Count matches between text and given list of words
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The input text to analyze
                words:
                  type: array
                  items:
                    type: string
                  description: List of words to check for matches
      responses:
        '200':
          description: Number of matched words in the input text
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: integer
                    description: Number of matched words
